### ISSUE TITLE
chorągwie zhp: menu wchodzi pod kategorie

### ISSUE THREAD

**Issue by szczot3k** [itwzhp/zhp-pl#1]
Wyszukiwarka aktualności ze strony ZHP wchodzi ponad listę z wyborem chorągwi na https://zhp.pl/aktualnosci
![image](https://user-images.githubusercontent.com/23485507/106788734-a154b780-6651-11eb-96d2-13763f8794a8.png)

Swoją drogą nie mam pojęcia czy zgłaszać błędy jeszcze na pspaczek/nowa-zhp czy itwzhp/zhp-pl xd

**Comment by pspaczek** [comment]
podgląd: https://develop.przemyslawspaczek.pl/aktualnosci
