### ISSUE TITLE
Błąd relatywnych odnośników przy własnych odnośnikach i linkach w postach

### ISSUE THREAD

**Issue by vuk92** [itwzhp/zhp-pl#102]
Problem występuje zarówno we własnych odnośnikach w menu jak i w poście przy łączu w tekście. Całość można zaobserwować na [stronie chorągwi białostockiej](https://bialostocka.zhp.pl/) W odnośniku e-chorągiew link do SP chorągwi jest jakoś modyfikowany i zamiast `https://gkzhp.sharepoint.com/sites/e-bialostocka` wrzuca `https://bialostocka.zhp.pl/gkzhp.sharepoint.com/sites/e-bialostocka` czyli dodaje domenę pomiędzy `https://` a resztę adresu. Podobnie dzieje się np. w poście odnośnie wyboru uzupełniającego do Rady naczelnej. W tekście jest "wniosek" który jest odnośnikiem do pliku SP, ale adres jest zmodyfikowany i dlatego też nie otwiera tego poprawnie. Wniosek wrzuciliśmy na stronę jako załącznik do pobrania jako łatkę, ale no problem istnieje i jest uciążliwy. Jakieś pomysły gdzie mogę tego szukać?

na starszej developerskiej stronie ze starym motywem wersji 1.8 problem nie występował, po aktualizacji do najnowszej 2023.02.06.07.33.33 problem występuje. Nie wiem czy problem powstał przy ostatniej, czy którejść z wcześniejszych aktualizacji. Dopiero teraz został zauważony.

**Comment by vuk92** [comment]
@karol-gro coś da się z tym ruszyć? :)

**Comment by Truzi** [comment]
25.08.2023
Podbijam, problem dalej występuje - zamiast podmienić url w atrybucie, tylko "dokleja" podstawiony customowy url

**Comment by vuk92** [comment]
Problem coraz bardziej problematyczny. Nie możemy na stronie chorągwi wrzucić działających odnośników ani do sharepointa, ani do safe from harm.

**Comment by kovansky** [comment]
Hej!

Przychodzę z podpowiedzią, bo właśnie siedzę nad nową stroną stołecznej i też napotkałem ten problem i zacząłem się zagłębiać w kod, żeby go rozwiązać i okazało się, że to tak naprawdę kinda _by design_ 😅

Problem znika, gdy w Personalizacji motywu (Dostosuj) wejdziemy sobie w Ustawienia motywu -> **Wydarzenia** i w polu `Dozwolone domeny` wklepiemy sobie domenę naszej strony (czyli np. bialostocka.zhp.pl)... i problem powinien zniknąć.

![image](https://github.com/itwzhp/zhp-pl/assets/16369776/a38eb993-4910-41e6-b273-e6899902c63f)

Umiejscowienie tego ustawienia jest niezwykle intuicyjne, ale faktycznie wpływa nie tylko na adresy mailowe, z których można tworzyć wydarzenia, ale też na to, jak motyw interpretuje linki 🙃

**Comment by vuk92** [comment]
Olbrzymie dzięki! To w sumie powinno być chyba dopisane go manuala odnośnie motywu :) (do rozważenia @szczot3k  :) )
