### ISSUE TITLE
Wdrożenie aktualizacji motyw z customowego źródła

### ISSUE THREAD

**Issue by qj0n** [itwzhp/zhp-pl#19]
Wykorzystanie https://github.com/YahnisElsts/plugin-update-checker w motywie do nasłuchiwania zamian w wersjach motywu. W przypadku zmiany wersji użytkownik dostanie komunikat o konieczności zaktualizowania motywu.

![Zrzut ekranu 2021-03-17 o 21 33 54](https://user-images.githubusercontent.com/12138170/111534694-9456d800-8768-11eb-8d59-817b3a963bf6.png)

**Comment by qj0n** [comment]
@pspaczek O ile dobrze pamiętam, wystarczy publiczny plik json i zip. Jeśli tak to mogę już przygotować na nie miejsce na Azure jakiś flow deploymentu, a potem dorobimy samo budowanie jsona i paczki jak będzie budowane

**Comment by pspaczek** [comment]
tak, to i plik html, ja to sobie na razie trzymam tu http://wordpress.przemyslawspaczek.pl/details.json
- zip teraz jest pusty,
- json zawiera wszystko co jest potrzebne do działania
- changelog chciałbym spróbować w miarę na bieżąco powadzić żeby było wiadomo co tam się zmieniło

fajnie gdyby adres nie był tak randomowy jak work.zhp.pl, może kiedyś będzie okazja zmienić to work na na coś ładnego albo idealnie byłoby pobawić się z mapowaniem routingu na serwerze i wpuszczać WordPressa tam gdzie trzeba.

**Comment by qj0n** [comment]
Najprościej będzie wrzucić to na jakiś Azure Blob Storage, wtedy adres z automatu to coś w stylu https://zhp-themes.z16.web.core.windows.net/. Jeśli chcemy to jakoś upiększyć to możemy puścić przez CDN i wtedy można dowolny hostname przypisać i ew. jakiś lepszy routing (np. w storage'u możemy mieć prefixy typu /dev/zhp-pl-theme itp.)

**Comment by pspaczek** [comment]
IMO bez znaczenia, może być ten "brzydki" adres, to i tak będzie wszystko pod spodem
