### ISSUE TITLE
Obrazki wyróżnione w Gutenbergu

### ISSUE THREAD

**Issue by arturlamali** [itwzhp/zhp-pl#24]
![obraz](https://user-images.githubusercontent.com/74903042/111869726-f722bc00-8980-11eb-8c96-f29dc885e749.png)

W stronie tworzonej w Gutenbergu niepoprawnie wyświetla się obrazek wyróżniony. Najlepiej ukryć go na samej stronie, bo funkcję tę rozwiązuje sekcja z tłem.

**Comment by arturlamali** [comment]
Plus w takim wypadku koniecznie musi działać to też jako og:image

**Comment by pspaczek** [comment]
Żeby og:image było ustawione prawidłowo trzeba dodać obrazek wyróżniony który nie wyświetli się na podstronie
