### ISSUE TITLE
Zmiana zhp.pl/organizacja /ewentualnie Guteneberg?

### ISSUE THREAD

**Issue by arturlamali** [itwzhp/zhp-pl#28]
na kafelku

Jest: Naczelniczka ZHP 
Powinno być: Naczelnik ZHP

+Może ten element mógłby być zrobiony w Gutenbergu? Wówczas zyskalibyśmy możliwość edycji/naprawy we własnym zakresie.

**Comment by arturlamali** [comment]
Pilne.

**Comment by pspaczek** [comment]
Poprawione, czeka na build

**Comment by pspaczek** [comment]
W temacie bloków Gutenberga to jest taki plan. Zacząłem nawet kodować blok Card ale wymaga on więcej zabawy.
