### ISSUE TITLE
menu poziome: otwieranie w nowej karcie

### ISSUE THREAD

**Issue by szczot3k** [itwzhp/zhp-pl#30]
Domyślnie rzeczy dodane do menu poziomego mają ustawiony target: _blank, więc otwierają się w nowej karcie. Nie widzę opcji zmiany tego, choć na zhp.pl ten błąd nie występuje.

Problem można zaobserwować chociażby na: http://tomaszowmaz.zhp.pl

**Comment by pspaczek** [comment]
żeby to naprawić na szybko linki powinny być wpisane `/aktualności`; 
w postach aplikacja powinna rozpoznać czy jest to wewnętrzny link (SPA), czy zewnętrzny nieobsługiwany przez Vue.js

nie zamykam, issues zanim nie dodam tego mechanizmu w pozostałe miejsca

**Comment by pspaczek** [comment]
Jeżeli w menu pojawi się link wewnętrzny np `http://tomaszowmaz.zhp.pl/aktualnosci` to aplikacja zamieni go na `/aktualnosci` i nie otworzy go w nowym oknie. Wszystkie linki z poza `http://tomaszowmaz.zhp.pl` powinny być otwierane w nowym oknie. Poprawki powinny pojawić się jako aktualizacja motywu do 1.1

**Comment by pspaczek** [comment]
@szczot3k jak zaktualizujesz motyw do 1.1 i wszystko będzie ok to zamknij proszę taska

**Comment by pspaczek** [comment]
Po weryfikacji na http://tomaszowmaz.zhp.pl/ widzę że poprawka działa. Zamykam.
