### ISSUE TITLE
losowe teksty: domyślne wartości

### ISSUE THREAD

**Issue by szczot3k** [itwzhp/zhp-pl#31]
Czy byłaby możliwość dodania domyślnych wartości do losowych tekstów? Albo opcje importu takowych, wraz z wartościami z zhp.pl?

**Comment by pspaczek** [comment]
http://wordpress.przemyslawspaczek.pl/export/zwizekharcerstwapolskiego.WordPress.random.xml export z zhp.pl, dodałem link do dokumentacji
