### ISSUE TITLE
wpisy: błędy podczas wysyłania linków/odświeżania

### ISSUE THREAD

**Issue by szczot3k** [itwzhp/zhp-pl#32]
Po dodaniu wpisu możliwe jest wejście na niego tylko i wyłącznie ze strony głównej. W momencie wrzucenia linku bezpośredniego do artykułu / odświeżeniu strony wyskakuje błąd "UPS, NIE MA TAKIEJ STRONY!".

Przykładowy link: http://tomaszowmaz.zhp.pl/2021/wesolego-alleluja (po odświeżeniu próbuje kierować na http://tomaszowmaz.zhp.pl/2021/04/09/wesolego-alleluja/).

**Comment by pspaczek** [comment]
bezpośrednie odnośniki są zgodne z stroną główną zhp.pl, należy skonfigurować je w WordPress następująco
Ustawienia/Bezpośrednie odnośniki/Własny format i wpisać `/%year%/%postname%/`

**Comment by szczot3k** [comment]
@pspaczek warto wrzucić to do dokumentacji, issue do zamknięcia

**Comment by pspaczek** [comment]
Dodane, zamykam
