### ISSUE TITLE
wpisy: HTTP 200, przy "UPS, NIE MA TAKIEJ STRONY" (#32)

### ISSUE THREAD

**Issue by szczot3k** [itwzhp/zhp-pl#33]
W przypadku kiedy strona nie może być wyświetlona przez błąd z konfiguracją bezpośrednich linków (#32) wysyłany jest kod HTTP 200, pomimo wyświetlenia komunikacie o błędzie "UPS, NIE MA TAKIEJ STRONY".

**Comment by pspaczek** [comment]
Powinno zostać rozwiązane w v1.1 motywu. Po wejściu na http://tomaszowmaz.zhp.pl/xd mamy w konsoli 404 
powiązane z https://github.com/itwzhp/zhp-pl/issues/32
