### ISSUE TITLE
Nie działają elementy strony głównej: Podstawowe informacje, Polecane

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#34]
Podstawowe informacje - niezależnie od dodania czegokolwiek w tym bloku nie są widoczne
Polecane - niezależnie od wybrania/nie wybrania kategorii cały blok nie jest widoczny

**Comment by kowalczyk-p** [comment]
Polecane udało się uruchomić (musi być więcej wpisów, warto by to dodać do instrukcji) ale podstawowe informacje nie działają dalej.

https://nowa.lublin.zhp.pl

**Comment by pspaczek** [comment]
@kowalczyk-p zarówno Polecane i Wydarzenia wymagają conajmiej 4 postów, informacja dodana do dokumentu.

**Comment by pspaczek** [comment]
@kowalczyk-p aktualizacja, która powinna naprawić sekcję "Podstawowe informacje" powinna się pojawić jako aktualizacja motywu do 1.1

**Comment by szczot3k** [comment]
@pspaczek aktualizacja 1.1 rozwiązała problem (http://tomaszowmaz.zhp.pl)

**Comment by kowalczyk-p** [comment]
@pspaczek potwierdzam, działa.
