### ISSUE TITLE
Jak możemy wprowadzić na głównej stronie głównej inne treści?

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#35]
Chcieli byśmy na stronie głównej mieć możliwość wprowadzenia innych rzeczy niż tylko te, które można skonfigurować. Przykładowo:
- Facebook
- baner związany z 1%
- film (nawet na zasadzie bloku "Poznaj ZHP" z zhp.pl)
- wyróżnione komunikaty przydatne w sytuacjach kryzysowych (np. w sytuacji wydarzeń jak w Suszku, na starej zhp.pl przez pewien czas wyróżniony był blok "Wychowujemy zgodnie z wartościami")

**Comment by pspaczek** [comment]
CC @arturlamali, to kwestia dla WKiP mieliśmy tylko dostarczyć to co było na projekcie dla Chorągwi/Hufców, pytanie co z wspomnianymi wyżej pytaniami.

**Comment by arturlamali** [comment]
Chorągwie i hufce powinny mieć możliwość zmiany Instagrama, Facebooka i film na swój. 
Jeśli chodzi o 1 procent, myślę, że najlepiej sprawdziłoby się wyróżnione miejsce obok Aktualności na głównej.
Jeśli chodzi o wyróżnione treści - no tutaj również powinny mieć możliwość podwieszenia innych wpisów.

**Comment by kowalczyk-p** [comment]
Temat jest pilny :) Chcieli byśmy mieć na stronie duży widget FB bo tam mamy najwięcej aktualności.

**Comment by pspaczek** [comment]
@arturlamali, @kowalczyk-p do motywu trafi sekcja sociali z głównej, rozmiary widgetów będą takie jak na głównej. Partnerzy tafia obok sociali. Partnerzy bez ROHiS 
![Zrzut ekranu 2021-05-15 o 13 03 03](https://user-images.githubusercontent.com/12138170/118358176-f328aa00-b57d-11eb-83c7-a65a5cb353eb.png)

**Comment by arturlamali** [comment]
@pspaczek a co w sytauacji, jesli hufiec nie ma insta? czy na miejscu może pojawić się Facebook? Plus czy jest możliwe, aby te moduły były tej samej wysokości? (facebook jest krótszy)

**Comment by pspaczek** [comment]
Widok bez FB i IG
![Zrzut ekranu 2021-05-15 o 18 47 15](https://user-images.githubusercontent.com/12138170/118371696-166b4d80-b5ae-11eb-94a6-df3a82a35fc2.png)

Widok FB i IG
![Zrzut ekranu 2021-05-15 o 18 52 48](https://user-images.githubusercontent.com/12138170/118371864-c8a31500-b5ae-11eb-9122-4936f71dac18.png)

Widok FB bez IG, tu do poprawy jeszcze szerokość FB :( 
![Zrzut ekranu 2021-05-15 o 19 10 56](https://user-images.githubusercontent.com/12138170/118372310-4cf69780-b5b1-11eb-9a71-9637f64d7c77.png)

Widok IG bez FB
![Zrzut ekranu 2021-05-15 o 19 07 56](https://user-images.githubusercontent.com/12138170/118372312-5122b500-b5b1-11eb-9a16-2c44f31cb4c8.png)


Konfiguracja na strona-główna
![Zrzut ekranu 2021-05-15 o 18 45 12](https://user-images.githubusercontent.com/12138170/118371919-14ee5500-b5af-11eb-86f3-de54ef341f6d.png)


@arturlamali zobaczę co da się zrobić w kwestii wysokości FB

**Comment by pspaczek** [comment]
Dodałem sekcję z wideo jak na głównej
![Zrzut ekranu 2021-05-17 o 17 54 37](https://user-images.githubusercontent.com/12138170/118518986-fb791480-b738-11eb-8adf-94e37842a12e.png)

FB można wyrównać ręcznie, nie wpisując wysokość bloku w ustawieniach
![Zrzut ekranu 2021-05-17 o 17 56 00](https://user-images.githubusercontent.com/12138170/118519206-324f2a80-b739-11eb-981b-686ec5e2daba.png)
