### ISSUE TITLE
Menu z listą jednostek

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#36]
1. Dlaczego to menu nie działa w taki sposób, że pozycje pierwszego poziomu są widoczne a pozycje drugiego poziomu rozwijają się na kliknięcie (tak jak jest to zrobione na zhp.pl)? W jaki sposób mamy skonfigurować to menu tak, jak wygląda to na zhp.pl?
2. Zewnętrzne linki z tego menu powinny być otwierane w nowym oknie.

**Comment by pspaczek** [comment]
1. Menu jednostek jest jednopoziomowym, bez funkcji mega menu. Wyłącznie menu główne posiada możliwość zagnieżdżania i tego nie planujemy zmieniać
2. I tak się dzieje z tego co sam klikałem

**Comment by kowalczyk-p** [comment]
1. A czemu nie może być takie jak na zhp.pl?
2. Jest ok.

**Comment by pspaczek** [comment]
![Zrzut ekranu 2021-04-21 o 20 48 21](https://user-images.githubusercontent.com/12138170/115605544-f1532a00-a2e2-11eb-9a76-35f4f23c6c54.png)
to jest menu jednostek i nie posiada więcej niż jednego poziomu, chyba że mowa i innym menu

**Comment by szczot3k** [comment]
@pspaczek jeżeli dobrze rozumiem Pawła chodzi o możliwość dodania trzech menu w górnym pasku. Ja nie byłem w stanie odtworzyć konfiguracji z zhp.pl.

**Comment by pspaczek** [comment]
Jeżeli tak, to takiej funkcji na razie nie planowałem. Rozmieściliśmy 3 menu w tym to dedykowane jednostką i na razie nie ma możliwość na szybko czegoś dodać.

**Comment by kowalczyk-p** [comment]
@pspaczek Chodzi dokładnie o takie menu jak wrzucił @szczot3k . Dokładnie takie jest na zhp.pl i nie wiem, czemu tu mamy inne, te szablony nie mają wspólnego kodu?

**Comment by pspaczek** [comment]
ten sam kod bazowy, z czasem theme zaczął żyć swoim życiem,
wynika to z tego że w zhp.pl sporo rzeczy jest zrobionych "z kodu", przy motywach potrzebowaliśmy dać większą władzę z poziomu WordPress'a

**Comment by kowalczyk-p** [comment]
Ale chyba na zhp.pl też jest to menu konfigurowane a nie na sztywno zaszyte w kodzie ;)

**Comment by pspaczek** [comment]
nie :D jest stałe, lista Chorągwi jest stała
