### ISSUE TITLE
Nie działa blok Galeria

### ISSUE THREAD

**Issue by arturlamali** [itwzhp/zhp-pl#37]
Po wstawieniu bloku Galerii nie wyświetla zdjęć poprawnie - zdjęcia pokazują się jako lista wypunktowana.

**Comment by pspaczek** [comment]
Działa do 6 kolumn, na mobile zawsze wymuszam 1 kolumnowy układ. 
![Zrzut ekranu 2021-05-17 o 20 44 24](https://user-images.githubusercontent.com/12138170/118540221-acd77480-b750-11eb-9a8d-2e997189401f.png)
