### ISSUE TITLE
Problem z odnośnikiem w stopce

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#40]
Na nowa.lublin.zhp.pl do menu w stopce dodałem własny odnośnik kierujący na https://zhp.pl/rodo. Niestety ten link zmieniany jest na link na stronie tzn. https://nowa.lublin.zhp.pl/rodo. Jak zrobię własny odnośnik do jakiejś innej domeny np. https://lubelska.zhp.pl/rodo to działa.

**Comment by pspaczek** [comment]
Powinno być ok po wydaniu wersji 1.2
