### ISSUE TITLE
Menu jednostek nie jest widoczne na telefonie

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#41]
Ponieważ tego menu nie widać na telefonie musimy treści, które w nim są powtórzyć w menu głównym a to zaprzecza sensowi istnienia tego menu.

**Comment by pspaczek** [comment]
na razie połączę te menu na mobile i schowam jednostki pod przyciskiem `Więcej`
![Zrzut ekranu 2021-05-17 o 20 08 34](https://user-images.githubusercontent.com/12138170/118536160-ab577d80-b74b-11eb-9df5-0d3c1c0c86b6.png)

**Comment by kowalczyk-p** [comment]
A czy zamiast więcej możemy wyświetlić po prostu nazwę tego menu? Więcej a pod nim jedna pozycja jest mało sensowne.

**Comment by pspaczek** [comment]
@kowalczyk-p jest tak jak prosiłeś
<img width="417" alt="Zrzut ekranu 2021-06-24 o 08 29 28" src="https://user-images.githubusercontent.com/12138170/123213437-4c152780-d4c6-11eb-85e0-c61caec9b9e8.png">

**Comment by kowalczyk-p** [comment]
Dzięki :)
