### ISSUE TITLE
Linki z podstawowych informacji otwierają się w nowym oknie

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#43]

**Comment by pspaczek** [comment]
`#`raczej nie powinien znajdować się w adresie URL, czy podałeś poprawne URL'e?  
![Zrzut ekranu 2021-04-30 o 22 16 37](https://user-images.githubusercontent.com/12138170/116749787-c020db00-aa01-11eb-9429-fdcfa690a9a5.png)

**Comment by kowalczyk-p** [comment]
@pspaczek chodzi o ten blok:
![image](https://user-images.githubusercontent.com/60511960/116797075-f6ce2280-aae1-11eb-904c-f2e7673bdbac.png)
