### ISSUE TITLE
Copyright w stopce jest linkiem

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#44]
To pewnie powinno być po prostu ujęte w instrukcji - copyright jest linkiem do strony o slug copyright.

PS. Na https://zhp.pl/copyright jest wskazanie maila helpdesk, który chyba nie jest już obsługiwany.

**Comment by pspaczek** [comment]
CC @arturlamali w temacie maila na zhp.pl

**Comment by pspaczek** [comment]
Dodane do dokumentacji
![Zrzut ekranu 2021-04-28 o 09 03 01](https://user-images.githubusercontent.com/12138170/116360772-8af96a80-a800-11eb-914e-8cbbe4f8e8ac.png)

**Comment by arturlamali** [comment]
Usuwamy helpdesk@zhp.pl, który kieruje do mailto:heldesk@zhp.pl, wstawiamy tylko helpdesk.zhp.pl, chyba, że @karol-gro proponujesz inne rozwiązanie? :D

**Comment by karol-gro** [comment]
Link https://helpdesk.zhp.pl będzie najlepszy
