### ISSUE TITLE
Strona 404 nie działa

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#45]
Zdefiniowałem stronę ze slug = undefined ale pod https://nowa.lublin.zhp.pl/404 nie widzę ani tytułu, ani obrazu wyróżniającego ani nic z tego co zdefiniowałem.

**Comment by pspaczek** [comment]
@kowalczyk-p wygląda jakby zdjęcie było zbyt małe do wyświetlenia, czy możesz spróbować zdjęcie większe od `768px`

**Comment by kowalczyk-p** [comment]
@pspaczek pomogło, jak ma szerokość dokładnie 768px (obrazek ściągany z zhp.pl/404) to nie działa ale dla większego jest ok. Może warto o tym wspomnieć w dokumentacji?

**Comment by pspaczek** [comment]
@kowalczyk-p dodane.
