### ISSUE TITLE
[regiony] Dołożenie listy akutalności

### ISSUE THREAD

**Issue by arturlamali** [itwzhp/zhp-pl#49]
Proszę jednak o dołożenie listy aktualności do motywu dla hufców, podobnie jak na zhp.pl

**Comment by pspaczek** [comment]
Podgląd
![Zrzut ekranu 2021-05-15 o 12 02 26](https://user-images.githubusercontent.com/12138170/118356416-71cd1980-b575-11eb-98df-af1637108b41.png)
Konfiguracja
![Zrzut ekranu 2021-05-15 o 12 02 53](https://user-images.githubusercontent.com/12138170/118357212-33d1f480-b579-11eb-9836-4a02bb821e79.png)
