### ISSUE TITLE
Poprawki w Dockerfile

### ISSUE THREAD

**Issue by qj0n** [itwzhp/zhp-pl#5]
Hej,
dobrze by było zrobić kilka poprawek w Dockerfile:
1. Te zmienne środowiskowe powinny być poza Dockerfile (np. w docker-compose lub z palca przy uruchamianiu). Dzięki temu będzie można zbudować obraz bez hardcode'owania URL-ów, a dopiero stawiając przypiąć do aplikacji
2. Multi-stage dockerfile. Aplikację dobrze by zbudować na pierwszym obrazie, przekopiować tylko z produkcyjnymi pakietami na drugi i tam odpalać. Taki obraz gotowy do uruchomienia można wgrać na registry githuba lub ew. dockerhuba
3. (nice to have) dobrze byłoby ściągać pakiety przed skopiowaniem kodu do kontenera. Idealna kolejność to (wersja na npm, bo nie znam yarna): 
   - kopiujesz package.json i package-lock, 
   - npm install, 
   - kopiujesz resztę kodu, 
   - npm build. 
Wtedy wszystko optymalnie się cache'uje przy lokalnym dewelopmencie. Na CI to akurat na jedno wychodzi, bo i tak buduje się zawsze od zera
4. Wyciąganie plików aplikacji z dockera. Najlepiej pewnie odpalić kontener z customowym entrypointem `true` (czyli de facto od razu się zamknie) i wtedy `docker cp` odpowiednie pliki. Jak będę wiedział, które pliki to dodam generowanie artefaktów w CI z nich

Jeśli będziesz potrzebował z tym pomocy to dawaj znać, możemy się zdzwonić i peer-programować tego Dockera. Ja potem ogarnę CI do tego procesu, ale wtedy chyba będzie trzeba trochę skomplikować flow gita, np. z mastera automatycznie wypuszczamy wersjonowane paczki, a dewelopment na feature branchach. Albo z mastera automatyczny deployment, z developa deployment developerski (tak, by WKiP mógł sobie przejrzeć zmiany przed akceptacją) a development na feature branchach. Ale to do obgadania

**Comment by pspaczek** [comment]
@qj0n generalnie publikacjia paczki na npm sprawia że mogłem skopiować do dockera tylko /packages/app, zmieniłem trochę dockera https://github.com/itwzhp/zhp-pl/commit/31b0900fba50bf021add46c6cd89ed9d7e7f4625
- zmienne są w .env (robiłem to z zamiarem użycia docker-compose), brakuje tam na pewno zmiennej dla **sentry** żeby można ją łatwo podmienić. Pewnie tam też powinny trafić NUXT_HOST i NUXT_PORT. Daj znać jak to powinniśmy skonfigurować.
- co do multi-stage brzmi dobrze, nie wiem teraz jak to zrobić (to mój pierwszy docker 🐳)
- generalnie to teraz jest tak
```
COPY /packages/app /usr/src/nuxt-app/
RUN yarn
RUN yarn build
```
powinno być pewnie
```
COPY /packages/app/package.json (yarn.lock jest w root dla całego monorepo, pewnie paczki powinny być bardziej niezależne żeby w /packages/app też był yarn.lock)
RUN yarn
... reszta kodu z /packages/app
RUN yarn build
```
- nie wiem czy chcesz wyciagać pliki potrzebne do działania aplikacji czy zbędnę :D generalnie nuxt ma swój folder `.nuxt` i tu jest cała aplikacja

**Comment by qj0n** [comment]
ponumerowałem uwagi ;)
1 i 2 zrobione w #8.
3 nie jest jakieś kluczowe, można to kiedyś dorobić (ale to tylko do lokalnego budowania).
4 do ustalenia, jak rozumiem trzeba jeszcze się nad tematem aplikacji "stand-alone" (bez dockera) pochylić. Nie wiem, czy to nie w ramach osobnego PR czy issue.

Myślisz, że można wtedy po zamknięciu tego PR-a zamknąć to issue?

**Comment by qj0n** [comment]
OK, to zamykam i spojrzę na temat CI/CD. W międzyczasie trzeba będzie ogarnąć temat przygotowania paczki stand-alone
