### ISSUE TITLE
Problem z blokiem plik

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#50]
Blok plik wyświetla się brzydko (przykład z zhp.pl/rodo):
![image](https://user-images.githubusercontent.com/60511960/117343108-40cd5480-aea4-11eb-92f5-fb3482227f0a.png)
Ten sam problem występuje w szablonie dla hufców.

**Comment by pspaczek** [comment]
Poprawione
![Zrzut ekranu 2021-05-17 o 19 49 43](https://user-images.githubusercontent.com/12138170/118534030-13589480-b749-11eb-83c2-bfb210062ae0.png)
