### ISSUE TITLE
Etykiety pod obrazkami wyróżniającymi

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#51]
Bardzo fajną funkcjonalnością jest to, że jeżeli obraz ustawiony jako obraz wyróżniający i ma ustawioną etykietę to pojawi się ona pod obrazem (jak na https://nowa.lublin.zhp.pl/kontakt) ale fajnie by było opisać takie rzeczy w dokumentacji :)

**Comment by pspaczek** [comment]
Dodane do dokumentacji
