### ISSUE TITLE
Filtr na kafelkach polecane

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#52]
Czy możemy zrobić tak aby ten kolorowy filtr na kafelkach był tylko pod tekstem a nie na całym kafelku? Strasznie brzydko to wygląda...
![image](https://user-images.githubusercontent.com/60511960/117347822-c99abf00-aea9-11eb-9864-e79bb92c8775.png)

**Comment by pspaczek** [comment]
jeżeli ma powstać design to CC @arturlamali musicie go przygotować,
możemy zrobić przełącznik na wersje bez tła
<img width="362" alt="Zrzut ekranu 2021-05-15 o 13 15 36" src="https://user-images.githubusercontent.com/12138170/118358559-a3e37900-b57f-11eb-8dea-0ea14bad8124.png">
lub użyć alternatywnej wersji tego bloku z projektu
<img width="694" alt="Zrzut ekranu 2021-05-15 o 13 17 06" src="https://user-images.githubusercontent.com/12138170/118358600-db522580-b57f-11eb-8bd7-828ebaf21a96.png">

**Comment by arturlamali** [comment]
No to chyba możemy zrobić przełącznik na wersje bez tła :)

**Comment by pspaczek** [comment]
k, przeniosłem to do wersji 1.3 motywu, nad 1.2 właśnie pracuję

**Comment by kowalczyk-p** [comment]
@pspaczek o taki będzie super:
![image](https://user-images.githubusercontent.com/60511960/119024824-cae8e300-b9a3-11eb-95ec-80a4ac9d9951.png)

**Comment by pspaczek** [comment]
Dodałem przełącznik `Tekst na kafelkach` domyślnie `true`
<img width="1358" alt="Zrzut ekranu 2021-06-19 o 18 21 12" src="https://user-images.githubusercontent.com/12138170/122648815-2507d000-d12b-11eb-8b7f-ac42cf1cbf7e.png">
odznaczony checkbox spowoduje wyrenderowanie tekstu pod kafelkami
<img width="1081" alt="Zrzut ekranu 2021-06-19 o 18 20 49" src="https://user-images.githubusercontent.com/12138170/122648806-16b9b400-d12b-11eb-8c58-1ecf2cc6c7f1.png">
