### ISSUE TITLE
wydarzenia na głównej

### ISSUE THREAD

**Issue by arturlamali** [itwzhp/zhp-pl#54]
czy po przeminięciu terminu wydarzenia mogłoby nie pojawiać się na głównej?

**Comment by pspaczek** [comment]
ta sekcja wygląda na niezarządzaną, obecnie są tylko 2 wydarzenia... jak usuniemy te minione to będą tylko zreplikowane dwa aktywne wydarzenia
![Zrzut ekranu 2021-06-19 o 18 23 48](https://user-images.githubusercontent.com/12138170/122648909-84fe7680-d12b-11eb-91d7-4198232f052f.png)
po poprawkach dopiszę usuwanie przeterminowanych wydarzeń ze slajdera

**Comment by pspaczek** [comment]
zrobione i już zbudowane na http://zhp.pl:4000/

**Comment by pspaczek** [comment]
dodać do Motyw ZHP
