### ISSUE TITLE
Po ustawieniu awataru nie bardzo działa strona

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#55]
W ustawieniach strony głównej jest pole "Awatar", jak go ustawimy to główna nie działa:

![image](https://user-images.githubusercontent.com/60511960/119015603-58730580-b999-11eb-98d1-57e4795ffc65.png)

**Comment by pspaczek** [comment]
@kowalczyk-p avatar działa bez problemu na stronie demo. Czy używasz instagrama? Avatar jest w sekcji instagram a do obsługi tej sekcji wymagana jest wtyczka Smash Balloon Instagram Feed, zaraz dodam do dokumentacji

**Comment by pspaczek** [comment]
dodałem zabezpieczenie, które powinno zapobiec temu błędowi w przyszłości
