### ISSUE TITLE
Jak możemy wyłączyć sekcję aktualności?

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#56]
Taki ficzer by się przydał, żeby je ukryć. Mój hufiec ma ich tak mało, że nie chcemy ich pokazywać na głównej.

**Comment by pspaczek** [comment]
dodałem do każdej sekcji, poza partnerami obecnie przełącznik `Widoczne`, pozwala ukryć sekcję na stronie głównej
![Zrzut ekranu 2021-06-18 o 07 47 56](https://user-images.githubusercontent.com/12138170/122512683-8172ce80-d009-11eb-87f7-20a3ff8552db.png)
