### ISSUE TITLE
Problemy z wyszukiwarką

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#57]
1. Jak wpiszemy szukaj w wyszukiwarkę to znajdujemy stronę szukaj ;)
![image](https://user-images.githubusercontent.com/60511960/119020148-30d26c00-b99e-11eb-854b-905632fa9451.png)

2. Na stronie szukaj nie działa wyszukiwarka.

3. Jak w wyszukiwarce znajdziemy stronę szukaj to szukamy undefined.
![image](https://user-images.githubusercontent.com/60511960/119019994-07194500-b99e-11eb-8537-79d1d2a08a5f.png)

4. Jak nic nie znajdziemy to przydał by się jakiś komunikat. 
![image](https://user-images.githubusercontent.com/60511960/119020598-b6561c00-b99e-11eb-98da-2433599a1b4f.png)

**Comment by pspaczek** [comment]
ad 1,2: użyj tej wtyczki https://wordpress.org/plugins/search-exclude/ i wyklucz z wyników wyszukiwania strony 
- Strona Główna
- Aktualności
- 404
- Szukaj

**Comment by pspaczek** [comment]
ad 4: poprawiłem komunikat o braku wyników
![Zrzut ekranu 2021-06-18 o 08 55 19](https://user-images.githubusercontent.com/12138170/122519903-48d7f280-d013-11eb-823a-24c13d3649f5.png)
