### ISSUE TITLE
Zmiana szerokości widgetu FB

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#58]
FB jeżeli nie ma Instagrama zajmuje 1/3 szerokości co źle wygląda - powinien zajmować w takiej sytuacji połowę szerokości.

![image](https://user-images.githubusercontent.com/60511960/119017593-78a3c400-b99b-11eb-9a1d-30065d195dee.png)

**Comment by pspaczek** [comment]
instagram (4/13), facebook (3/12), partnerzy (5/12)
<img width="1666" alt="Zrzut ekranu 2021-06-20 o 19 43 02" src="https://user-images.githubusercontent.com/12138170/122683561-44bcf800-d200-11eb-813a-6ff8663979b9.png">
w pozostałych przypadkach 2 * (6/12)
<img width="1662" alt="Zrzut ekranu 2021-06-20 o 19 45 52" src="https://user-images.githubusercontent.com/12138170/122683585-703fe280-d200-11eb-92db-6eb0d32a6dc6.png">
<img width="1664" alt="Zrzut ekranu 2021-06-20 o 19 46 35" src="https://user-images.githubusercontent.com/12138170/122683588-7209a600-d200-11eb-96b7-8bccfea4d76d.png">
