### ISSUE TITLE
Problemy z blokiem partnerzy

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#59]
Przy małej ilości partnerów (mniej niż 4) karuzela z logami się nie wyświetla. Żeby ją pokazać musimy wrzucać te same grafiki po kilka razy co powoduje, że ta karuzela wygląda słabo. Czy zamiast karuzeli jak mamy mniej niż 4 elementy możemy je po prostu pokazać jeden pod drugim.

Dodatkowo mamy problem z banerami, które są poziome, np. ROHiS czy bon turystyczny. Na zhp.pl ROHiS jest wrzucony pod karuzelą jako stały element. Jak możemy to rozwiązać na naszych stronach?

**Comment by pspaczek** [comment]
Dla mniej niż 4 karuzela zostaje. Na mobile widzimy 1 logo w karuzeli
<img width="412" alt="Zrzut ekranu 2021-06-20 o 20 52 36" src="https://user-images.githubusercontent.com/12138170/122685052-81412180-d209-11eb-9c27-3f366c6b9f4a.png">
Na desktop te logotypy układają się tak jakby miało ich być w więcej. Karuzela zostaje zablokowana.
<img width="1095" alt="Zrzut ekranu 2021-06-20 o 20 52 48" src="https://user-images.githubusercontent.com/12138170/122685057-843c1200-d209-11eb-891e-f802170cb6c4.png">

**Comment by pspaczek** [comment]
> Dodatkowo mamy problem z banerami, które są poziome, np. ROHiS czy bon turystyczny. Na zhp.pl ROHiS jest wrzucony pod karuzelą jako stały element. Jak możemy to rozwiązać na naszych stronach?

Nie ma takiej opcji, dodam do partnerów field 'Kategoria dla banerów' gdzie będzie możliwy wybór logotypów które będą wyświetlane poziomo jak ROHiZ

**Comment by pspaczek** [comment]
Do ustawień dodałem `Kategoria banerów`
![Zrzut ekranu 2021-06-22 o 19 27 18](https://user-images.githubusercontent.com/12138170/122981750-5fc36f80-d39a-11eb-9cf4-a3caabab7f7e.png)
Banery zostaną wyświetlone jeden pod drugim
![Zrzut ekranu 2021-06-22 o 19 27 03](https://user-images.githubusercontent.com/12138170/122981802-72d63f80-d39a-11eb-8346-5d3882a0cced.png)
