### ISSUE TITLE
Blok Gutenberg akordeon - literówki

### ISSUE THREAD

**Issue by arturlamali** [itwzhp/zhp-pl#6]
W edytorze:
![obraz](https://user-images.githubusercontent.com/74903042/108072760-95acbc00-7067-11eb-9bf1-9e771cd4972e.png)

**tutuł > tytuł**

W podglądzie:
![obraz](https://user-images.githubusercontent.com/74903042/108072806-a4936e80-7067-11eb-9f7c-336909218fcd.png)

**<br>**

**Comment by pspaczek** [comment]
@arturlamali tytuł nie powinien zawierać HTML'a dlatego tam jest też zwykłe pole tekstowe a nie edytor :D 
Typo zafixowane
