### ISSUE TITLE
Podpisy pod zdjęciami wyróżniającymi i w galerii

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#61]
Pod zdjęciami wyróżniającymi do podpisu dodawane jest "fot." a w galerii nie. Możemy to ujednolicić? 
![image](https://user-images.githubusercontent.com/60511960/119024548-78a7c200-b9a3-11eb-9818-d2ee450609a8.png)

![image](https://user-images.githubusercontent.com/60511960/119024580-82c9c080-b9a3-11eb-9422-95b8e636e05b.png)

**Comment by pspaczek** [comment]
dodałem `fot.` wszędzie 
![Zrzut ekranu 2021-06-17 o 16 54 45](https://user-images.githubusercontent.com/12138170/122421632-cc023580-cf8c-11eb-9f1c-8280c1018a18.png)
