### ISSUE TITLE
Daty w polecanych

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#62]
Czy możemy przenieść datę do polecanej aktualności a usunąć ją z wyróżnionej treści przy bloku dołącz do nas?

![image](https://user-images.githubusercontent.com/60511960/119027984-3b453380-b9a7-11eb-93d1-465fb5618866.png)

**Comment by pspaczek** [comment]
Dodałem pole `Typ` dla tych postów. Można przełączyć pomiędzy Card/Post
![Zrzut ekranu 2021-06-18 o 19 02 34](https://user-images.githubusercontent.com/12138170/122594762-c0377180-d067-11eb-9a28-eb8dc1b7c908.png)
