### ISSUE TITLE
Nie wysyłają się powiadomienia o nowych wydarzeniach

### ISSUE THREAD

**Issue by arturlamali** [itwzhp/zhp-pl#63]
Nie docierają maile z potwierdzeniem na promocja@zhp.pl z dodanymi wydarzeniami przez formularz na stronie

**Comment by kowalczyk-p** [comment]
A jak te maile są wysyłane? Tam jest jakaś wtyczka do SMTP?

**Comment by pspaczek** [comment]
Hej, wtyczka `Powiadomienia` w wersji free nie wspiera wysyłania notyfikacji w przypadku `custom post types` a takim są eventy. Dopiszę do funkcji eventów to ręcznie.

**Comment by pspaczek** [comment]
Powiadomienia powinny już się wysyłać. 
![Zrzut ekranu 2021-06-26 o 14 45 05](https://user-images.githubusercontent.com/12138170/123513465-b0ceae80-d68d-11eb-8c90-58d9c998acf3.png)

**Comment by pspaczek** [comment]
jest na produkcji już bo to funkcjonalność wordpressa
