### ISSUE TITLE
Nie ładuje się strona na mobile

### ISSUE THREAD

**Issue by kowalczyk-p** [itwzhp/zhp-pl#64]
Strona nie ładuje nam się na telefonach ani w przeglądarce przy włączonej emulacji urządzenia mobilnego. Przykład na lublin.zhp.pl.

Nie działa nam na produkcji więc pilne ;) @pspaczek 

![image](https://user-images.githubusercontent.com/60511960/127537229-1c4a32ea-9571-4ce9-9ac7-72d076afddcd.png)

**Comment by pspaczek** [comment]
@kowalczyk-p na szybko, wyłącz FB bo sypie errorami, naprawię to w weekend

**Comment by pspaczek** [comment]
chociaż u mnie motyw.przemyslawspaczek.pl ładuje się bez problemu :(

**Comment by pspaczek** [comment]
k, @kowalczyk-p czy sprawdzałeś czy to nie coś z waszym serwerem. motyw.przemyslawspaczek.pl ładuje się normalnie. Patrząc na to co sie dzieje z network wygląda jakbyście mieli ograniczone requesty

**Comment by kowalczyk-p** [comment]
Nasz serwer jest na atthost.pl, nie mamy tam prawie nic do przestawienia. No i w widoku "desktopowym" ładuje się dobrze.

**Comment by pspaczek** [comment]
wydaje mi się że wina jednak leży po winie serwera, wywala się po 29 requestach, możesz zmienić limity w `php.ini`

**Comment by kowalczyk-p** [comment]
Ale na zwykłym masz nawet więcej niż 29 requestów + wszystkie na mobile zwracają 200.

**Comment by pspaczek** [comment]
W kodzie nie widzę błędów, w konsoli spada błąd tylko dla FB. Motyw działa lokalnie i na motyw.przemyslawspaczek.pl. Nie jestem w stanie pomóc bez kopi tej strony 1:1 jakimś Dupilicatorem czy innym narzędziem tego typu. Możesz też zrobić zrzut bazy danych i kopie plików i wysłać mi na kontakt[at]przemyslawspaczek.pl

**Comment by kowalczyk-p** [comment]
Ten 29 URL na którym mówisz, że się wywala tak na prawdę się ładuje: https://lublin.zhp.pl/wp-json/wp/v2/posts?per_page=1&_embed=true. Problem polega na tym, że po załadowaniu zawiesza się JS, lepiej to widać w FF:
`collect@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/277b66f.js:2:18377
mount@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/277b66f.js:2:18165
T@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/277b66f.js:2:7395
value@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/277b66f.js:2:8680
value@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/277b66f.js:2:29068
mounted/<@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/7260e23.js:1:61986
pe/<@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/8fe41c5.js:2:13367
ce@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/8fe41c5.js:2:12811
promise callback*oe@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/8fe41c5.js:2:12899
pe@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/8fe41c5.js:2:13430
t.prototype.$nextTick@https://nowa.lublin.zhp.pl/wp-content/themes/zhp-pl/_nuxt/8fe41c5.js:2:36624
render/_.beforeEnter@https://no…`

Wysłałem Ci backup strony.

**Comment by pspaczek** [comment]
k, znalazłem problem, naprawię go i jutro powinien wyjść update motywu

**Comment by pspaczek** [comment]
@kowalczyk-p na szybko powinno pomóc dodanie jednego partnera ale nie jako banner

**Comment by pspaczek** [comment]
dobra, poszedł update motywu do 1.7

**Comment by kowalczyk-p** [comment]
Działa, dzięki :)
