### ISSUE TITLE
Logo Chorągwi i Hufca w nagłówku

### ISSUE THREAD

**Issue by puszkow** [itwzhp/zhp-pl#68]
Logo chorągwi i logo hufca do nagłówka (można spróbować ustawić jako karuzelę  loga(stacjonarną) z logotypami z odpowiedniej kategorii) 

+ oczywiście podlinkowanie do odpowiedniej strony

https://motyw.slaska.zhp.pl/wp-content/uploads/2022/01/naglowki.png

**Comment by writ3it** [comment]
Czy takie rozwiązanie będzie wystarczające?

![obraz](https://user-images.githubusercontent.com/42292507/194734074-2845a237-1031-42de-b834-9e29e1814959.png)
![obraz](https://user-images.githubusercontent.com/42292507/194734080-50d42218-d6e2-42dc-b90d-950a84bab7a7.png)

**Comment by puszkow** [comment]
Hej,
myślę, że jak najbardziej 🙂


Czuwaj

hm. Andrzej Zawalski

Zespół Wsparcia Informatycznego

Chorągwi Śląskiej ZHP


Hufiec ZHP Sosnowiec


________________________________________________

Aleja Harcerska 3b. 41-500 Chorzów

tel. 606-967-820



www.slaska.zhp.pl<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.historyczna.slaska.zhp.pl%2F&data=02%7C01%7Candrzej.zawalski%40slaska.zhp.pl%7C0ccb2c4b21c54dd1016508d7c74ebed1%7Ce1368d1e39754ce6893dfc351fd44dcd%7C0%7C0%7C637197013338593732&sdata=e2UmTOdhFSuFpZfkuTerCSRYiG876CgUGJB3qJVuuyM%3D&reserved=0>

***@***.***>



***@***.***



***@***.***

Administratorem Pani/Pana danych osobowych jest Związek Harcerstwa Polskiego Śląska Chorągiew z siedzibą w Katowicach przy ul. Aleji Korfantego 8, ("ZHP Ch.Śląska"). Pani/Pana dane osobowe będą przetwarzane w celu nawiązania i utrzymywania kontaktu, w tym kontaktu w związku z podjętą z ZHP  Ch.Śląską współpracą. Szczegółowe informacje dotyczące przetwarzania Pani/Pana danych osobowych przez ZHP znajdzie Pani/Pan pod adresem www.zhp.pl/rodo<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.zhp.pl%2Frodo&data=02%7C01%7Candrzej.zawalski%40slaska.zhp.pl%7C0ccb2c4b21c54dd1016508d7c74ebed1%7Ce1368d1e39754ce6893dfc351fd44dcd%7C0%7C0%7C637197013338593732&sdata=njaZ5gZ%2FGbbGpOy5n%2Bp9BmLyCzncUrQAE1GlaJghgkE%3D&reserved=0>. W przypadku jakichkolwiek pytań może Pani/Pan skontaktować się z ZHP Ch.Sląska, pod podanym powyżej adresem siedziby. Może Pani/Pan również skontaktować się bezpośrednio z wyznaczonym przez nas inspektorem ochrony danych pod adresem ***@***.******@***.***>.

________________________________
Od: writ3it ***@***.***>
Wysłane: niedziela, 9 października 2022 04:01
Do: itwzhp/zhp-pl ***@***.***>
DW: Andrzej Zawalski ***@***.***>; Author ***@***.***>
Temat: Re: [itwzhp/zhp-pl] Logo Chorągwi i Hufca w nagłówku (Issue #68)


Czy takie rozwiązanie będzie wystarczające?

[obraz]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42292507%2F194734074-2845a237-1031-42de-b834-9e29e1814959.png&data=05%7C01%7Candrzej.zawalski%40zhp.net.pl%7Cc80202b134df43e3fdcc08daa99a1e52%7Ce1368d1e39754ce6893dfc351fd44dcd%7C0%7C0%7C638008776661233535%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rOuRov71MoVdfhZdwR4i8R1ANoG6MRQD3bVKMx9%2FKzk%3D&reserved=0>
[obraz]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42292507%2F194734080-50d42218-d6e2-42dc-b90d-950a84bab7a7.png&data=05%7C01%7Candrzej.zawalski%40zhp.net.pl%7Cc80202b134df43e3fdcc08daa99a1e52%7Ce1368d1e39754ce6893dfc351fd44dcd%7C0%7C0%7C638008776661233535%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oZNGf7MejFBb%2BRVh3RbaDkB47S7W2fV9JOtrSL32uWE%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fitwzhp%2Fzhp-pl%2Fissues%2F68%23issuecomment-1272431494&data=05%7C01%7Candrzej.zawalski%40zhp.net.pl%7Cc80202b134df43e3fdcc08daa99a1e52%7Ce1368d1e39754ce6893dfc351fd44dcd%7C0%7C0%7C638008776661389763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jBUJvrq3YJGXtdsut9TldNemmo90QaUNVPycZkLIa8E%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT6QXV4ARXDJHYHOYOVQJ6DWCIRN3ANCNFSM5MMWMBLA&data=05%7C01%7Candrzej.zawalski%40zhp.net.pl%7Cc80202b134df43e3fdcc08daa99a1e52%7Ce1368d1e39754ce6893dfc351fd44dcd%7C0%7C0%7C638008776661389763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BjLElBVM%2BS5Ubkx%2BjBZuh68O4NjErGxODvPabYQB1ws%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>


Współadministratorami danych osobowych jest Związek Harcerstwa Polskiego oraz wszystkie chorągwie Związku Harcerstwa Polskiego. Dane kontaktowe oraz adres każdego ze Współadministratorów dostępny jest na stronie internetowej https://bip.zhp.pl. Dane osobowe będą przetwarzane w celu nawiązania i utrzymywania kontaktu mailowego, w tym kontaktu w związku z podjętą ze Współadministratorami współpracą lub korespondencją z danym Współadministratorem/Współadministratorami. Szczegółowe informacje dotyczące przetwarzania danych osobowych przez Współadministratorów znajdują się pod adresem www.zhp.pl/rodo lub na stronach poszczególnych Współadministratorów. W przypadku jakichkolwiek pytań prosimy kontaktować się bezpośrednio ze Współadministratorem. Kontaktować się można również bezpośrednio z wyznaczonym przez nas inspektorem ochrony danych pod adresem ***@***.***
