### ISSUE TITLE
Błąd aktualności roku 2022 - błąd 404

### ISSUE THREAD

**Issue by puszkow** [itwzhp/zhp-pl#69]
Występuje problem z wpisami aktualności kolejnego roku - nie działa - błąd 404

**Comment by kowalczyk-p** [comment]
@pspaczek Jesteś w stanie pomóc?

**Comment by kowalczyk-p** [comment]
https://github.com/itwzhp/zhp-pl/blob/eda53797f709e0b15df6fbfc57fb950830ebbe3c/packages/app/nuxt.config.js#L45 Może to przez to?

**Comment by pspaczek** [comment]
cześć @kowalczyk-p tak masz rację, to pewnie ta linijka. Problem z motywami jest taki że te "linki" tworzą się w trakcie builda. Na zhp.pl build przebiega sprawnie. Z motywami trzeba trochę pokombinować żeby wszystko działało. W tym tyg zerknę na to i postaram się A. pozbyć tego hacka, B. usprawnić budowanie motywu dla ZHP. Chcę odgrzebać w głowie jak to się robiło.

**Comment by kowalczyk-p** [comment]
@pspaczek będziemy bardzo wdzięczni, strona mojego hufca jest nieaktualizowalna, w aktualnej sytuacji nie mam jak spojrzeć bo działamy ostro z pomocą a jednocześnie bardzo przydało by się coś na niej dodać.

**Comment by kowalczyk-p** [comment]
@pspaczek jak tam, udało się?

**Comment by pspaczek** [comment]
http://wordpress.przemyslawspaczek.pl/changelog.html @kowalczyk-p poszedł update 1.8 ⚠️ przebudowałem tylko aplikację, więc ścieżki powinny być wspierane przez motyw. Jeżeli by coś nie działało pisz na kontakt[at]przemyslawspaczek.pl i skorzystaj z wersji 1.7

**Comment by kowalczyk-p** [comment]
@pspaczek na http://wordpress.przemyslawspaczek.pl/zhp-pl-1.8.zip jest Internal Server Error

**Comment by pspaczek** [comment]
naprawione
