### ISSUE TITLE
Wyszukiwarka nie działa

### ISSUE THREAD

**Issue by duzymaju** [itwzhp/zhp-pl#77]
W nowym motywie głównym, bardzo eksponowanym elementem (znajduje się na górze strony głównej) jest wyszukiwarka. Niestety ani w [wersji ogólnozwiązkowej](https://zhp.pl/szukaj?search=jest) ani [tej dla jednostek](https://nowysacz.zhp.pl/szukaj?search=jest) nie działa. Co ciekawe, niepusta lista wyników jest zwracana z API (przykład z frazą "jest" [dla zhp.pl](https://work.zhp.pl/wp-json/wp/v2/search?_embed=true&subtype[]=post&subtype[]=page&subtype[]=event&search=jest), [dla nowysacz.zhp.pl](https://nowysacz.zhp.pl/wp-json/wp/v2/search?_embed=true&subtype[]=post&subtype[]=page&subtype[]=event&search=jest)), tylko nic tego później nie renderuje - czy to przez błąd w kodzie, czy przez niedokończoną funkcjonalność.

Co ciekawe, dodatkowo [strony związkowej](https://zhp.pl/szukaj?search=jest) w ogóle nie można otworzyć przez link (server error), w odróżnieniu od [stron jednostek](https://nowysacz.zhp.pl/szukaj?search=jest).

**Comment by karol-gro** [comment]
Wydaje mi się naprawione, dajcie znać jeśli trzeba otworzyć ponownie
