### ISSUE TITLE
Brak możliwości wykorzystania kolumn w treści strony

### ISSUE THREAD

**Issue by duzymaju** [itwzhp/zhp-pl#80]
W edytorze styli Wordpressa istnieje możliwość używania kolumn, które niestety nie są wspierane przez arkusz styli motywu, choć ich style są banalnie proste do implementacji - opisano to np. w artykule ["Styling the Gutenberg Columns Block"](https://css-tricks.com/styling-the-gutenberg-columns-block/).

Być może istnieją również inne elementy używane w edytorze, które warto byłoby ostylować na stronie.

**Comment by pspaczek** [comment]
Polecam użycie bloku `zhp/column` lub dodanie tych styli do swojego wordpressa. Dodatkowo kod jest otwarty, zawsze można zostać bohaterem i zaimplementować te banalnie proste style :)

**Comment by duzymaju** [comment]
Funkcjonalność działa od wersji [2023.01.18.11.24.43](https://github.com/itwzhp/zhp-pl/releases/tag/2023.01.18.11.24.43).
